### ISSUE TITLE
Error: 160

### ISSUE THREAD

**Issue by Clubberry** [CreativeDo/ZXPInstaller#11]
What means error 160?

**Comment by cameronmcefee** [comment]
Hi @Clubberry `160` [appears to be “Failed to parse the file”](http://www.adobeexchange.com/resources/19#errors). My best guess is that the file may be corrupt. Where did you get it from?

**Comment by cameronmcefee** [comment]
Also thank you for reporting this. It looks like we need to add `160` to the list of codes for messages.

**Comment by Clubberry** [comment]
Hi, @cameronmcefee . It's appears for me with every *.zxp file. For that situation — Uber Column.
Screenshot included.

P.S. I can record the video.

P.S.S. I have a chance for solving this problem?
![image 2015-11-06 at 10 36 31](https://cloud.githubusercontent.com/assets/581441/10992823/76b5b6a8-8472-11e5-91b7-4f182c43318b.png)

**Comment by nvkzNemo** [comment]
Hi, @Clubberry 

try to rename <extension>.*zxp* to <extension>.*zip*

and unzip it to the `C:\Users\<user>\AppData\Roaming\Adobe\CEP\extensions\<extension name>`

**Comment by nvkzNemo** [comment]
@cameronmcefee 
160 — There is a file operation error when installing this add-on.

**Comment by cameronmcefee** [comment]
Hi @Clubberry,

@nvkzNemo's advice *should* work. However, if it doesn't let us know.

For my own research, would you mind making a video and be sure that you include launching the installer as part of the video?

**Comment by Clubberry** [comment]
@nvkzNemo some of uber plugins does not working after renaming .zxp to .zip. Your way don't helped me.

@cameronmcefee http://cl.ly/image/3S2d3v1n1G3Z

**Comment by nvkzNemo** [comment]
@Clubberry что значит не помог?
т.е. вы их переименовали в зип, распаковали в указанную папку, как я сказал, перезапустили фотошоп и они не появились в фотошопе?

**Comment by Clubberry** [comment]
@nvkzNemo Да, Антон, не помогла ручная установка.
Во-первых, у меня вообще не было папки CEP. Во-вторых, когда я переименовал расширение .zxp на .zip, то WinRAR вообще отказался открывать ваш плагин UberColumn как архив. С плагином UberFace такая махинация сработала, но папки CEP не оказалось. Я создал её, но всё равно никаких изменений.

**Comment by nvkzNemo** [comment]
А какая версия Фотошопа?

**Comment by Clubberry** [comment]
CC 2015 от 22.07.2015. r.168.

**Comment by nvkzNemo** [comment]
Для CC 2014 и 2015 они распаковываются в `C:\Users\<user>\AppData\Roaming\Adobe\CEP\extensions\<название раширения>`
Для CC в `C:\Users\<user>\AppData\Roaming\Adobe\CEPServiceManager4\extensions`

Либо точно такие же папки
`C:\Program Files (x86)\Common Files\Adobe\CEP\extensions`
и `C:\Program Files (x86)\Common Files\Adobe\CEPServiceManager4\extensions`

должно работать хоть в Program Files хоть в User

распаковывать лучше стандартной вондовсовской распаковкой (правой кнопкой → извлечь всё...)

**Comment by Clubberry** [comment]
C:\Program Files (x86)\Common Files\Adobe\CEPServiceManager4\extensions
По этому пути есть папка. В неё извлёк UberFaces и UberLine. Ни один плагин не работает.
Установлен GuideGuide в данной папке и он отображается в списке расширений в фотошопе.

**Comment by nvkzNemo** [comment]
`C:\Program Files (x86)\Common Files\Adobe\CEPServiceManager4\extensions` только для CC (не для СС 2014 или 2015)

Если у вас СС 2015, то нужна папка `C:\Program Files (x86)\Common Files\Adobe\CEP\extensions`

**Comment by Clubberry** [comment]
@nvkzNemo Сработало. Создал папку CEP в директории для CC 2015, туда получилось установить UberFaces и UberLine, но посредством переименования .zxp в .zip. С UberColumn такого не выходит сделать. Пишет, что файл повреждён.

Спасибо за потраченное время!

**Comment by cameronmcefee** [comment]
@nvkzNemo @Clubberry were you able to install successfully? Can this issue be closed?

**Comment by nvkzNemo** [comment]
Yeah, I think the problem is solved

**Comment by cameronmcefee** [comment]
:+1:
