### ISSUE TITLE
Error 603

### ISSUE THREAD

**Issue by dottzilla** [CreativeDo/ZXPInstaller#14]
I am trying to use ZXP to install UberColumns for Photoshop CC, but keep getting an Error 603. Can someone tell me what this error means?

**Comment by nvkzNemo** [comment]
@dottzilla Error 603 — failed to do online license check.

Please try to use UberManager https://github.com/nvkzNemo/UberManager/releases/tag/v.0.2.1

**Comment by dottzilla** [comment]
I got this error when trying with UberManager: Installation failed 
because UberManager could not parse the ZXP file

Dottie McLeroy
Dottzilla Design
Quality Design...Affordable Rates
www.dottzilla.com
405-615-3484



------ Original Message ------

**Comment by nvkzNemo** [comment]
@dottzilla please try to use this version of UberColumns https://www.dropbox.com/s/ho5xn4qnxgx470n/ubercolumns-1.1.zxp?dl=0

**Comment by dottzilla** [comment]
I got it! I installed thru Adobe Exchange and the CC app and just used 
it in PS. This is wonderful!! Thank you so much for creating this 
script!! You are a lifesaver!!


Dottie McLeroy
Dottzilla Design
Quality Design...Affordable Rates
www.dottzilla.com
405-615-3484



------ Original Message ------
