### ISSUE TITLE
zxp not compatiable with PPRO 2015.3

### ISSUE THREAD

**Issue by jimmi-wipster** [CreativeDo/ZXPInstaller#21]
Hi there,

I have a zxp that is setup for PPRO 2015.3 but wont install via the zxp installer, but it will install via the ExManCmd.

I have set the versions to "9.0 - 10.9" in the manifest.

Any help would be great.

**Comment by cameronmcefee** [comment]
@jimmi-wipster Can you provide me with a few things so I can try this out? I'm not familiar with (I presume) Premiere personally.

- Can you send a zxp for me to use to test things? cm@cameronmcefee.com. I'll dispose of it after testing, if you're willing to take my word for it :)
- Do you have a link to where you got the ExManCmd? This is currently the only source I know of: https://www.adobeexchange.com/resources/28. You are not the first person to [mention it does not support certain apps](https://github.com/Adobe-CEP/CEP-Resources/issues/60#issuecomment-227782246).
- Could you supply an example install command so I can make sure the correct command is being generated?

**Comment by jimmi-wipster** [comment]
Thanks Cameron, I just emailed you. Might go to spam with the attachment.

**Comment by jimmi-wipster** [comment]
I hadn't updated to the latest version of the zxp installer, now it is working. 

Your a legend Cameron! Keep rocking.
