### ISSUE TITLE
PS CC 2015.5

### ISSUE THREAD

**Issue by ADukal** [CreativeDo/ZXPInstaller#22]
As you probably already know after the recent update to CC 2015.5 the installation is broken, it doesn't work at all.
On Windows, the panels previously installed at **_C:\Program Files (x86)\Common Files\Adobe\CEP\extensions_**
actually are going to **_C:\Program Files (x86)\Common Files\Adobe\CEPServiceManager4\extensions_**
so they are not detected by Photoshop.
The question is:
any plan to update the brilliant ZXP INSTALLER?

Many thanks in advance!

**Comment by cameronmcefee** [comment]
Hi @ADukal,

I published an update with the latest version of `ExManCmd` that Adobe has available (to my knowledge). Be sure to grab the latest from http://zxpinstaller.com/ or https://github.com/CreativeDo/ZXPInstaller/releases/tag/1.5.0.

> actually are going to C:\Program Files (x86)\Common Files\Adobe\CEPServiceManager4\extensions

Lol, no kidding? I didn't dig in far enough to discover that.

**Comment by ADukal** [comment]
Awesome. First try with that latest version worked smoothly.

**_C:\Program Files (x86)\Common Files\Adobe\CEPServiceManager4\extensions_**
is where panels are going with the previous ZXP Installer after the CC 2015.5 update

Regards.
