### ISSUE TITLE
ZXP INSTALLER

### ISSUE THREAD

**Issue by sudesh89** [CreativeDo/ZXPInstaller#23]
zxp installer is unable to install any extensions.help me sort about this

**Comment by cameronmcefee** [comment]
Hi @sudesh89,

Can you be more specific about what isn't working? Are you receiving an error?

**Comment by sudesh89** [comment]
when i drop a file in zxp installer it just loads,loads & loads......it doesn't go further

**Comment by cameronmcefee** [comment]
I've experienced this myself a few times. I've usually found that restarting my computer, then trying to install my extension before launching any Adobe products helps. If you downloaded the ZXPInstaller before last week, I suggest downloading again as well (there's been an update for the CC 2015.5 apps).

Give that a try and let me know if it resolves things.

**Comment by sudesh89** [comment]
facing the same problem

**Comment by cameronmcefee** [comment]
:( Unfortunately I'm not sure what's up and am unable to debug at this time. You can give https://github.com/nvkzNemo/UberManager/releases a try.

**Comment by psdcovers** [comment]
Hi cameronmcefee,

the problem appears to be that CC 2015.5 is a completely new release version 17.  The current zxp installer only signs up to v16.

Look at the "Debugging Unsigned Extensions" section in https://github.com/Adobe-CEP/CEP-Resources/wiki/CEP-5-HTML-Extension-Cookbook-for-CC-2014#development_debugging

For CC2015,5, you need to edit HKEY_CURRENT_USER/Software/Adobe/CSXS.7

**Comment by cameronmcefee** [comment]
@psdcovers As far as I understand what you're suggesting, what you are referring to is unrelated to installing extensions, it's a debugging concern. You shouldn't be asking users to edit their debug settings to install an extension, or doing it for them.

**Comment by cameronmcefee** [comment]
Have you redownloaded ZXPInstaller recently? I published an update a few days ago that updated the ExManCmd to the latest release which supports the new locations for the recent app updates. If you have further issues, please open a new issue so we can discuss there.

**Comment by psdcovers** [comment]
@cameronmcefee, I downloaded it minutes ago while running tests.

zxpinstaller placed the plugin in the older CEP path so something in our ZXP is not properly conveying to zxpinstaller that it is compatible with CC 2015.5 and should be installed in the newer Plug-ins path.

Now to dig through our zxp to figure out where we made a mistake...

**Comment by cazoobi** [comment]
The old CEP location still works fine on the Mac CC2015.5. If I remember correctly, the plugins dir has always been supported too, its not a new location just an alternative one.

**Comment by cameronmcefee** [comment]
Yep, that's correct. Let's discontinue or move that conversation, as it's off topic from this thread.

**Comment by cameronmcefee** [comment]
Looks like there's a plausible explanation in #17 due to a dependency not being installed. I'll dig into it this week to see if its an error that can be caught (hopefully so).

**Comment by cameronmcefee** [comment]
@sudesh89 can you confirm if you're using Windows or OS X?

**Comment by sudesh89** [comment]
windows os

**Comment by cameronmcefee** [comment]
Thanks @sudesh89, I'm able to reproduce this on Windows.

Unfortunately, despite an evening of trying to debug, I haven't yet found a solution to the problem. Here's where I'm at this evening:

The logger shows the install process beginning, then hangs without further output. @jakkor mentioned in #17 that a dependency needed to be installed before extension installation could continue when using ExManCmd via the command prompt. Testing this myself on a fresh VM, when running via the command prompt, I get a message stating that `MSVCP140.dll` (and a few others) is missing, [which appears to be a C++ related dependency](https://www.youtube.com/watch?v=n-CgFu71PTk), so I'm going to call this account corroborated for now.

The trick is, `spawn` doesn't seem to catch this error. Normally, I'd catch the error and then provide a message that suggests installing the appropriate files, however if I can't catch the error, I can't detect the problem and provide feedback.

I'm going to ask some node-ish folks if they've got ideas, but for the moment I'm stumped. This is a bit out of my wheelhouse.

@sudesh89 You could try installing https://www.microsoft.com/en-us/download/details.aspx?id=48145, then running the ZXPInstaller again. Keeping in mind that I don't technically have evidence this is your issue and that this comes with the disclaimer that I'm not a Windows dev so I can't guarantee success or the safety of this advice. However, reading through the page I'm guessing it's safe to install and worst case will just add extra files you'll never need.

**Comment by GothicGourdGirl** [comment]
I recently downloaded ZXP Installer to add a plug-in because stupid Adobe CC Extention Manager keeps saying I don't have Photoshop (which of course, I do).  Yes, I downloaded the Mac version, and downloaded it twice, restarting my computer, etc.  When I open the extension, it says it had been installed, but I can't find it ANYWHERE.  Not in the CEP file (which is still working for 2015.5, and it seems all my other extensions are fine there, and not anywhere else.... 
If there was a way to extract it into a folder, I could put it there myself, but I don't see an option for choosing where to extract it to.  Any help would be excellent because this plug-in is an Impasto Painter suite, and as a painter, it would really enhance my work.  Thanks!

**Comment by cameronmcefee** [comment]
Hi @GothicGourdGirl,

I think it will take a little back-and-forth discussion to resolve this, so please [<kbd>create a new thread</kbd>](https://github.com/CreativeDo/ZXPInstaller/issues/new) so we can discuss without pinging all the fine folks here.

When you do, please clarify something: You mentioned that some things work in 2015.5 but other things don't. Please clarify the specific things that are working and where.
