### ISSUE TITLE
Installation failed because ZXPInstaller could not update the database.

### ISSUE THREAD

**Issue by debelop13** [CreativeDo/ZXPInstaller#24]
Hello!

I try to install in a completly new Windows (without previous installations) and ZXPInstaller shows "Installation failed because ZXPInstaller could not update the database. It should not be possible to receive this error", but really installation has been done correctly.

Someone knows what happens? Where adobe saves databases?

 Thanks.

**Comment by cameronmcefee** [comment]
Hi @debelop13,

Sorry for the trouble and thank you for proving that it is in fact possible. So to clarify, you received that error but the installation worked?

ZXPInstaller uses and Adobe tool to do the installing, so the errors are pulled from [their error codes](https://helpx.adobe.com/extension-manager/using/extension-manager-error-code-reference.html). Unfortunately, they don't clearly explain what they mean by "database," so I don't really have a clue 😦.

If the extension shows up, you're probably fine. Whatever "database" they're referring to is likely not going to be used by ZXPInstaller anyway. If the extension doesn't show up, my first guess would be to try restarting your computer and try again in hopes it was a fluke. If that doesn't fix things, Adobe's suggestion is to [consult their forums](https://forums.adobe.com/community/creative_cloud/add-ons/exchange), however I'm skeptical that will yield results.

**Comment by debelop13** [comment]
Yes, I receive this error but installation works always.

And yes, I wrote a suggestion in Adobe Forum two weeks ago and I am still waiting for a response..

Thanks anyway!

**Comment by cameronmcefee** [comment]
> I am still waiting for a response

Yeah… that doesn't surprise me at all. I'm glad you've got it working though. Closing this for now. Feel free to reopen if you discover anything negative as a result.
