### ISSUE TITLE
ZXP Installer Says it has Extracted my Extension, but Where Is It? 

### ISSUE THREAD

**Issue by GothicGourdGirl** [CreativeDo/ZXPInstaller#26]
I recently downloaded ZXP Installer to add a plug-in because stupid Adobe CC Extention Manager keeps saying I don't have Photoshop (which of course, I do). Yes, I downloaded the Mac version, and downloaded it twice, restarting my computer, etc. When I open the extension, it says it had been installed, but I can't find it ANYWHERE. The new extension is not to be found in the CEP file folder (where all my other extensions are still located, and working in Photoshop 2015.5 just fine).
If there was a way to extract it into a folder, I could put it there myself, but I don't see an option for choosing where to extract it to. 
I have opened Photoshop, looked in the Window/Extensions, and the extension isn't listed there. I've looked at other folders, just in the off-chance I'd find the missing extension, but it is lost.  Either it wasn't truly extracted, or it was saved somewhere I can't find it. Any help would be excellent because this extension is an Impasto Painter suite, and as a painter, it would really enhance my work. Thanks!

**Comment by cameronmcefee** [comment]
Sorry for the trouble! My goal with these questions is to determine whether you're experiencing a bug with ZXPInstaller (unlikely), a bug with the Extension installer manifest, or might be running into confusion.

1. Are you sure the version of the extension you are installing supports CC 2015.5? If it supports another version of something you have installed, it's possible the "success" message is for that other application.

2. Let's figure out where the files are going. Depending on how the installer is configured and the operating system you're using, there are a handful of places the files might be:

  ### Windows
  C:\Users\<USERNAME>\Program Files (x86)\Common Files\Adobe\<CEP>\extensions
  C:\Users\<USERNAME>\Program Files\Common Files\Adobe\<CEP>\extensions

  ### OS X
  /Library/Application Support/Adobe/<CEPFOLDER>/extensions/
  /Users/<USERNAME>/Application Support/Adobe/<CEPFOLDER>/extensions/

  Those are the most likely places you will find the extension files. I'm guessing they will either be named after the extension or something that looks like `com.something.something`. If you find something that looks like your extension, please let me know.

**Comment by GothicGourdGirl** [comment]
I found the files. The extension was extracted, so I manually moved it into my Photoshop's CEP folder. I have yet to check Photoshop to see if it's there, but I imagine it is.

I can't remember where I found the file...I was just opening all the folders related to Adobe...shoulda made a note.

Thanks for your help. It should work fine now. If it doesn't, it's the extension, and not your excellent handy program!!!

Stacy



On Aug 22, 2016, at 2:46 PM, Cameron McEfee <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the trouble! My goal with these questions is to determine whether you're experiencing a bug with ZXPInstaller (unlikely), a bug with the Extension installer manifest, or might be running into confusion.

  1.  Are you sure the version of the extension you are installing supports CC 2015.5? If it supports another version of something you have installed, it's possible the "success" message is for that other application.

  2.  Let's figure out where the files are going. Depending on how the installer is configured and the operating system you're using, there are a handful of places the files might be:

Windows

C:\Users<USERNAME>\Program Files (x86)\Common Files\Adobe<CEP>\extensions
C:\Users<USERNAME>\Program Files\Common Files\Adobe<CEP>\extensions

OS X

/Library/Application Support/Adobe//extensions/
/Users//Application Support/Adobe//extensions/

Those are the most likely places you will find the extension files. I'm guessing they will either be named after the extension or something that looks like com.something.something. If you find something that looks like your extension, please let me know.

-

**Comment by cameronmcefee** [comment]
👍  I'm glad you found them. Here are a couple additional things for consideration:

- If you get a "invalid signature" error, it means you've modified the files while moving them. It's a security feature and the only way to fix it is to re-install.

- If it still doesn't show up in Photoshop, open the extension folder again and look for `CSXS/manifest.xml`. Inside will be tag called `HostList` which lists the applications and versions supported. If this doesn't list your version, that'll explain why it doesn't show up. Please keep in mind that you can't modify the files (as mentioned above), so don't try to just add your version :)

**Comment by GothicGourdGirl** [comment]
Thanks for the extra tips!! Very kind of you.

All the best,

Stacy

On Aug 23, 2016, at 1:27 PM, Cameron McEfee <notifications@github.com<mailto:notifications@github.com>> wrote:


? I'm glad you found them. Here are a couple additional things for consideration:

  *   If you get a "invalid signature" error, it means you've modified the files while moving them. It's a security feature and the only way to fix it is to re-install.

  *   If it still doesn't show up in Photoshop, open the extension folder again and look for CSXS/manifest.xml. Inside will be tag called HostList which lists the applications and versions supported. If this doesn't list your version, that'll explain why it doesn't show up. Please keep in mind that you can't modify the files (as mentioned above), so don't try to just add your version :)

-
