### ISSUE TITLE
Silent install

### ISSUE THREAD

**Issue by doctorwho92** [CreativeDo/ZXPInstaller#28]
Is there a way I can silent install an ZXPInstaller.app package via command line, for mass deployment purposes? I need to push out a plugin to a lot of machines, and I want to do something like:

/tmp/ZXPInstaller.app/Contents/MacOS/Electron -noui -verbose > /var/log/ZXPInstaller.log

Thanks,

Alan.

**Comment by cameronmcefee** [comment]
Hi @doctorwho92,

Check out Adobe's ExManCmd. It's what ZXPInstaller uses under the hood. https://www.adobeexchange.com/resources/28
