### ISSUE TITLE
Uninstall Extension?

### ISSUE THREAD

**Issue by NectarMan** [CreativeDo/ZXPInstaller#3]
Hi your program works really well, but i had an issue with one of the plugins. how can i uninstall or find the installed zxp files? thanks, much appreciated

**Comment by SheepDomination** [comment]
How can one uninstall or find the installed zxp files is a feature that should be filled.

**Comment by Maxoos** [comment]
Currently uninstalling isn't available, but it is definitely possible.

You could manually uninstall an extension by deleting it from:

MacOS:
Launch Terminal and run this command:
open /Library/Application\ Support/Adobe/CEP/extensions/

Windows 64:
C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\

Windows 32:
C:\Program Files\Common Files\Adobe\CEP\extensions\

**Comment by SheepDomination** [comment]
One can uninstall the Official Adobe Extension Manager without any repercussions ?

**Comment by Maxoos** [comment]
If you have Adobe Extension Manager which was discontinued you should be able to use it to uninstall. Yes, that feature would have been nice, but currently there is no such effort.

**Comment by SheepDomination** [comment]
Effort as in others input for the tool, correct ?

**Comment by Maxoos** [comment]
Yes well no one is working on it, so if you'd like to have a go please do and submit a pull request.

**Comment by SheepDomination** [comment]
No one is working on it, because many up until recently are becoming aware that Adobe as discontinued Extension Manager; it appears Photoshop users are slow to adapt to the changes in Photoshop.

**Comment by Qwertyfly** [comment]
in app/src/installer.js

if you change
CMD_PREFIX+"install"
to
CMD_PREFIX+"remove"

it should handle uninstall

**Comment by SheepDomination** [comment]
I recently had a ZXP file to install for PhotoshopCC-2015, it didn't install, I got a 411 error ?

**Comment by cameronmcefee** [comment]
Closing this issue, as uninstallation is beyond the scope of this project for now.

**Comment by Jolg42** [comment]
:+1: @Maxoos for deleting the extension from `/Library/Application\ Support/Adobe/CEP/extensions/` :smiley:
