### ISSUE TITLE
Install extension per user

### ISSUE THREAD

**Issue by dungvt** [CreativeDo/ZXPInstaller#34]
Hi all,
Zxp installer is calling Exman to install extension at all user folder (C:\Program Files (x86)\Common Files\Adobe\CEP\extensions)
But, i want install it to user folder at roaming folder: C:\Users\{User}\AppData\Roaming\Adobe\CEP\extensions
What solution i can use?

Thanks for reading!

**Comment by cameronmcefee** [comment]
Hi @dungvt,

ZXPInstaller is very minimal so it doesn't offer any configuration options. What you want to do won't be possible through ZXPInstaller directly. I think the fastest workaround would be to install and then move the files to where you want them, however this might not be a practical solution if you're a developer wanting this for your users.

**Comment by cameronmcefee** [comment]
👍  You can also make it a little less manual with an installation script to do the copying. I wrote my own based loosely on https://github.com/undavide/PS-Installer, which allows you to decide where it goes.
