### ISSUE TITLE
Installation failed because it the ZXPInstaller could not check the license online.

### ISSUE THREAD

**Issue by daveblohm** [CreativeDo/ZXPInstaller#35]
The title is the error message. I am connected to the internet.

**Comment by cameronmcefee** [comment]
Unfortunately the Adobe command line utility that ZXPInstaller uses under the hood doesn't provide any clearer errors than that. It's been my experience that this error is usually false and there is no license to actually check, however an actual solution is unclear. Not great news, I know :(

The best suggestions I can offer:

- If you have the Extension Manager installed, uninstall it. It sometimes conflicts with the Adobe command line utility.

- Ask the extension developer if they offer a manual install option.

- Try a different installer that doesn't use the command line utility like https://github.com/nvkzNemo/UberManager
