### ISSUE TITLE
Command-line option?

### ISSUE THREAD

**Issue by TGBX12** [CreativeDo/ZXPInstaller#37]
Adobe's Extension Manager could be worked with from the command-line. This was useful in a situation like ours where we need to pre-install some extensions in entire rooms of computers, for all users.
https://helpx.adobe.com/extension-manager/using/command-line.html
I have not been able to find ZXPInstaller's command-line tool(s) or anything that would replicate the same functionality.
e.g. zxpinstall -install /Users/username/extension.zxp

**Comment by cameronmcefee** [comment]
Hi @TGBX12,

ZXPInstaller is just a GUI that uses Adobe's Exman [under the hood](https://github.com/CreativeDo/ZXPInstaller/tree/master/app/bin/WINDOWS) (the CLI remnant of the Extension Manager). If you aren't aware that the Exman exists and is still viable, this may be what you're looking for: https://www.adobeexchange.com/resources/28
