### ISSUE TITLE
AD Impastoshop installation

### ISSUE THREAD

**Issue by nrjanoes** [CreativeDo/ZXPInstaller#38]
Greetings to all!
I've been trying to install AD Impastoshop with ZXPinstaller but it seems that it takes quite some time.
The installer keeps saying "installing your extension" with nothing happening.
OS: win7 32bit

Any thoughts?
nrjanoes

**Comment by cameronmcefee** [comment]
Hi @nrjanoes,

Unfortunately, that's not enough info to make any sort of analysis with (not your fault, the installer doesn't offer any more info either). I've seen this happen with my own projects and in most cases a restart of my computer would resolve the issue. Beyond that there's unfortunately not much more info to debug with :(

**Comment by nrjanoes** [comment]
Well restarting the pc didn't help. The issue remains.

**Comment by cameronmcefee** [comment]
It looks like there has been a new version of ExManCmd so I've published a new version at http://zxpinstaller.com/. Give that a try.

**Comment by nrjanoes** [comment]
In my case there was a Microsoft framework missing. After I installed it I was able to complete the installation.
