### ISSUE TITLE
Does not work with Photoshop CC2018

### ISSUE THREAD

**Issue by JulesMc** [CreativeDo/ZXPInstaller#39]
Hi guys, 

Are you planning on updating the ZXPinstaller to work with the recently updated Photoshop CC2018?

**Comment by cameronmcefee** [comment]
Hi @JulesMc, so far as I have tested, ZXPInstaller is working fine with CC 2018. If your extension isn't installing, the developer of your extension probably has not updated their installer file to allow it to be installed in CC 2018. Be sure to check with them to see if they have an updated .zxp file.

**Comment by cameronmcefee** [comment]
It looks like there has been a new version of ExManCmd so I've published a new version at http://zxpinstaller.com/. Give that a try.

**Comment by JulesMc** [comment]
Thanks so much Cameron!!!!
Will test ASAP!

**Comment by cameronmcefee** [comment]
If you tried it and got an error, try downloading again. The previous version included a bug that caused the success message to get printed as an error.

**Comment by JulesMc** [comment]
Hi Cameron, 
It is still inconsistent. Sometimes it gives an error but actually installs the extension, like you mentioned, but sometimes it gives a success message, but the extension isn't installed.

**Comment by cameronmcefee** [comment]
Can you check the version you have? You can do this by hovering your mouse over the bottom right corner of the app window. If nothing shows up, you've got an old version. I published a new one today which fixed a bug that sounds kind of like what you described.

**Comment by JulesMc** [comment]
I think the very latest version you uploaded around the time or right before my message is the good one! Thank you so much for your time and helping all of us!
