### ISSUE TITLE
This installer does not support Adobe CC 2018 version.

### ISSUE THREAD

**Issue by mds-charu** [CreativeDo/ZXPInstaller#40]

**Comment by cameronmcefee** [comment]
Hi @mds-charu, so far as I have tested, ZXPInstaller is working fine with CC 2018. If your extension isn't installing, the developer of your extension probably has not updated their installer file to allow it to be installed in CC 2018. Be sure to check with them to see if they have an updated .zxp file.

**Comment by cameronmcefee** [comment]
It looks like there has been a new version of ExManCmd so I've published a new version at http://zxpinstaller.com/. Give that a try.

**Comment by mds-charu** [comment]
Hi, I have tried new installer but it fails to install an extension.

**Comment by cameronmcefee** [comment]
It looks like there was a bug in the latest version causing the success message to be printed as an error, if you check for your extension, it should be installed. You can download the latest from the link above which no longer includes this bug.
