### ISSUE TITLE
Installation Failed Because ZXPinstaller could not update the database

### ISSUE THREAD

**Issue by sniperfull** [CreativeDo/ZXPInstaller#41]
Installation failed because ZXPInstaller could not update the database. It should not be possible to receive this error.

thats the error i get when trying to install a .zxp file....

Windows 10 64Bit ... ran ZXPinstaller as admin...

**Comment by cameronmcefee** [comment]
I guess it's time to update that message then. Sorry, @sniperfull. Unfortunately, Adobe doesn't give [a clear explanation of that error](http://www.adobeexchange.com/resources/19#errors) beyond "Failed to update the database".

The best I can do is suggest you restart your computer and ensure you're connected to the internet to try to cover your bases and try again. You can also use https://github.com/nvkzNemo/UberManager which I believe does not rely on the Adobe command line tool that ZXPInstaller uses.

**Comment by sniperfull** [comment]
Thanks UberManager worked for me !
there seems to be a issue with ZXPInstaller tried restarting and disabling firewall ... tried it all couldnt resolve the issue

**Comment by cameronmcefee** [comment]
I'm glad you got it working!
