### ISSUE TITLE
Does not detect Illustrator 2019

### ISSUE THREAD

**Issue by glennwilton** [CreativeDo/ZXPInstaller#52]
When only Illustrator CC2019 is installed the installer will report that the ZXP file is not compatible with the version, Even though its set in the manifest file.

If an older version is installed, such as CC2015 it will install fine, and run fine on CC1029 without an issue so I suspect its the installer and not the manifest xml settings

Is there an update from Adobe which can be incorporated to fix this issue or is it the manifest,

**Comment by cameronmcefee** [comment]
Hi @glennwilton,

I agree this sounds like exmancmd (what ZXPInstaller uses to install) might be out of date. I'll take a look. If you want to verify in the meantime (and you're comfortable with the command line) you can try it out yourself: https://partners.adobe.com/exchangeprogram/creativecloud/support/exman-com-line-tool.html

**Comment by glennwilton** [comment]
I'll have to test tonight on a VM with a fresh install of Illustrator.

**Comment by glennwilton** [comment]
Just did a clean install on windows 10 VirtualBox, Downloaded the latest version of Creative Cloud, Installed Illustrator CC2019 and it installed the ZXP file ok. 

I see that you have committed #ExManCmd to 3.1.28 so it looks like that fixed it.

**Comment by cameronmcefee** [comment]
Ugh, sorry, I got distracted just as I published that build and was on my way here to let you know. Yes, you should be able to download the latest version and be back in action: http://zxpinstaller.com/

**Comment by glennwilton** [comment]
Awesome, Thanks ! keep up the good work!!
